// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agojvddqyfcozjxrllav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb2p2ZGRxeWZjb3pqeHJsbGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQzNDEsImV4cCI6MjA2NTU4MDM0MX0.KJMCgI9VRTu71Ez4-Xfd6AtHh96UdhAb5OnUbvZuLmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});